import type { ImportType } from '../../imports/importCenterApi';
import {
  createClassSectionFromForm,
  createCourseFromForm,
  createDepartmentFromForm,
  deactivateClassSection,
  deactivateCourse,
  deactivateDepartment,
  listAssessmentTypes,
  listClassSections,
  listCourses,
  listDepartments,
  listEnrollments,
  listPrograms,
  updateClassSectionFromForm,
  updateCourseFromForm,
  updateDepartmentFromForm,
} from '../api/academicApi';
import {
  createInstructorFromForm,
  createStudentFromForm,
  deactivateInstructor,
  deactivateStudent,
  listInstructors,
  listStudents,
  updateInstructorFromForm,
  updateStudentFromForm,
} from '../api/peopleApi';
import {
  createDeviceFromForm,
  createRoomFromForm,
  createRoomStationFromForm,
  deactivateDevice,
  deactivateRoom,
  deactivateStation,
  listDevices,
  listRoomStations,
  listRooms,
  loadRoomStationReadiness,
  updateDeviceFromForm,
  updateRoomFromForm,
  updateStationFromForm,
} from '../../facility/facilityApi';
import type { EntityConfig } from '../types';

const available = (note?: string) => ({ status: 'available' as const, note });
const deferred = (note: string) => ({ status: 'deferred' as const, note });
const unsupported = (note?: string) => ({ status: 'unsupported' as const, note });

function buildListFeatures(options: Partial<EntityConfig['listFeatures']> = {}): EntityConfig['listFeatures'] {
  return {
    supportsQuery: false,
    supportsStatusFilter: false,
    supportsPagination: true,
    defaultPageSize: 20,
    pageSizeOptions: [20, 50, 100],
    statusOptions,
    ...options,
  };
}

const statusOptions = [
  { label: 'ACTIVE', value: 'ACTIVE' },
  { label: 'INACTIVE', value: 'INACTIVE' },
];

const genderOptions = [
  { label: 'Nam', value: 'MALE' },
  { label: 'Nữ', value: 'FEMALE' },
];

const roomTypeOptions = [
  { label: 'LAB', value: 'LAB' },
  { label: 'CLASSROOM', value: 'CLASSROOM' },
  { label: 'ONLINE', value: 'ONLINE' },
  { label: 'HYBRID', value: 'HYBRID' },
];

const facilityStatusOptions = [
  { label: 'ACTIVE', value: 'ACTIVE' },
  { label: 'INACTIVE', value: 'INACTIVE' },
  { label: 'MAINTENANCE', value: 'MAINTENANCE' },
  { label: 'ARCHIVED', value: 'ARCHIVED' },
];

const stationStatusOptions = [
  { label: 'ACTIVE', value: 'ACTIVE' },
  { label: 'INACTIVE', value: 'INACTIVE' },
  { label: 'MAINTENANCE', value: 'MAINTENANCE' },
  { label: 'RESERVED', value: 'RESERVED' },
];

const deviceTypeOptions = [
  { label: 'LAB_PC', value: 'LAB_PC' },
  { label: 'LAPTOP', value: 'LAPTOP' },
  { label: 'TABLET', value: 'TABLET' },
  { label: 'SERVER', value: 'SERVER' },
];

const deviceStatusOptions = [
  { label: 'ACTIVE', value: 'ACTIVE' },
  { label: 'INACTIVE', value: 'INACTIVE' },
  { label: 'MAINTENANCE', value: 'MAINTENANCE' },
  { label: 'RETIRED', value: 'RETIRED' },
  { label: 'LOST', value: 'LOST' },
];

export const importEntityKeyByType: Partial<Record<ImportType, EntityConfig['key']>> = {
  STUDENTS: 'students',
  INSTRUCTORS: 'instructors',
  COURSES: 'courses',
  SUBJECTS: 'courses',
  CLASS_SECTIONS: 'classSections',
  ENROLLMENTS: 'enrollments',
  ROOMS: 'rooms',
  STATIONS: 'stations',
  DEVICES: 'devices',
};

export const masterDataEntities: EntityConfig[] = [
  {
    key: 'departments',
    label: 'Khoa / phòng ban',
    group: 'Academic',
    primaryKey: 'department_id',
    description: 'Đơn vị học thuật dùng để gắn môn học, giảng viên và chương trình.',
    fields: [
      { name: 'department_code', label: 'Mã đơn vị', required: true, placeholder: 'VD: FFA', fieldKind: 'code', fieldSize: 'sm' },
      { name: 'department_name', label: 'Tên đơn vị', required: true, placeholder: 'Viện Tài chính - Kế toán', fieldKind: 'longName', fieldSize: 'lg' },
      { name: 'parent_department_id', label: 'ID đơn vị cha', type: 'number', fieldKind: 'id', fieldSize: 'sm' },
      { name: 'status', label: 'Trạng thái', type: 'select', defaultValue: 'ACTIVE', options: statusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'department_id', label: 'ID' },
      { key: 'department_code', label: 'Mã' },
      { key: 'department_name', label: 'Tên' },
      { key: 'parent_department_id', label: 'ID cha' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listDepartments(params),
      create: (form) => createDepartmentFromForm(form),
      update: (entityId, form) => updateDepartmentFromForm(entityId, form),
      deactivate: (entityId) => deactivateDepartment(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'programs',
    label: 'Chương trình đào tạo',
    group: 'Academic',
    primaryKey: 'program_id',
    description: 'Danh mục chương trình đào tạo dùng để gắn sinh viên.',
    fields: [],
    createNote: 'API hiện có endpoint xem danh mục chương trình đào tạo; chưa có endpoint tạo mới.',
    columns: [
      { key: 'program_id', label: 'ID' },
      { key: 'program_code', label: 'Mã CTĐT' },
      { key: 'program_name', label: 'Tên chương trình' },
      { key: 'program_level', label: 'Bậc đào tạo' },
      { key: 'department_code', label: 'Đơn vị' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: unsupported('Chưa có endpoint tạo chương trình đào tạo trong master-data API.'),
      update: unsupported('Chưa có endpoint cập nhật chương trình đào tạo trong master-data API.'),
      deactivate: unsupported('Chưa có endpoint ngưng sử dụng chương trình đào tạo trong master-data API.'),
      readOnly: true,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: { list: ({ params }) => listPrograms(params) },
  },
  {
    key: 'courses',
    label: 'Môn học',
    group: 'Academic',
    primaryKey: 'course_id',
    description: 'Danh mục môn học gắn với khoa/phòng ban.',
    fields: [
      {
        name: 'department_id',
        label: 'Đơn vị quản lý',
        type: 'select',
        valueType: 'number',
        required: true,
        lookup: 'departments',
        allowManualLookupFallback: true,
        fieldKind: 'id',
        fieldSize: 'sm',
      },
      { name: 'course_code', label: 'Mã môn', required: true, placeholder: 'VD: ACC101', fieldKind: 'code', fieldSize: 'sm' },
      { name: 'course_name', label: 'Tên môn', required: true, fieldKind: 'longName', fieldSize: 'lg' },
      { name: 'credit', label: 'Số tín chỉ', type: 'number', fieldKind: 'numeric', fieldSize: 'xs' },
      { name: 'course_type', label: 'Loại môn', fieldKind: 'select', fieldSize: 'sm' },
      { name: 'status', label: 'Trạng thái', type: 'select', defaultValue: 'ACTIVE', options: statusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'course_id', label: 'ID' },
      { key: 'course_code', label: 'Mã' },
      { key: 'course_name', label: 'Tên' },
      { key: 'department_code', label: 'Đơn vị' },
      { key: 'credit', label: 'TC' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listCourses(params),
      create: (form) => createCourseFromForm(form),
      update: (entityId, form) => updateCourseFromForm(entityId, form),
      deactivate: (entityId) => deactivateCourse(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'courseOfferings',
    label: 'Mở môn theo học kỳ',
    group: 'Academic',
    primaryKey: 'course_offering_id',
    description: 'Môn học được mở trong học kỳ. Hiện được tạo tự động khi tạo lớp học phần.',
    fields: [],
    createNote: 'Chưa có endpoint CRUD riêng cho mở môn theo học kỳ; tạo lớp học phần sẽ tự tạo course_offering nếu cần.',
    columns: [
      { key: 'course_offering_id', label: 'ID' },
      { key: 'offering_code', label: 'Mã mở môn' },
      { key: 'course_code', label: 'Mã môn' },
      { key: 'term_code', label: 'Học kỳ' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: unsupported('Surface này chưa được nối API riêng.'),
      create: unsupported('Tạo mới diễn ra gián tiếp khi tạo lớp học phần.'),
      update: unsupported('Chưa có workflow cập nhật mở môn theo học kỳ.'),
      deactivate: unsupported('Chưa có workflow ngưng sử dụng mở môn theo học kỳ.'),
      readOnly: true,
    },
    listFeatures: buildListFeatures({ supportsPagination: false }),
    api: {},
  },
  {
    key: 'classSections',
    label: 'Lớp học phần',
    group: 'Academic',
    primaryKey: 'class_section_id',
    description: 'Nhóm lớp sinh viên đăng ký học/thi, gắn với môn học và học kỳ.',
    fields: [
      { name: 'class_code', label: 'Mã lớp học phần', required: true, placeholder: 'VD: ACC101-01', fieldKind: 'code', fieldSize: 'sm' },
      { name: 'class_name', label: 'Tên lớp học phần', required: true, fieldKind: 'longName', fieldSize: 'lg' },
      {
        name: 'course_id',
        label: 'Môn học',
        type: 'select',
        valueType: 'number',
        required: true,
        lookup: 'courses',
        integer: true,
        min: 1,
        allowManualLookupFallback: false,
        fieldKind: 'id',
        fieldSize: 'sm',
      },
      { name: 'term_id', label: 'ID học kỳ', type: 'number', required: true, integer: true, min: 1, helperText: 'Nhập ID hiện có trong hệ thống.', fieldKind: 'id', fieldSize: 'sm' },
      { name: 'capacity', label: 'Sức chứa', type: 'number', integer: true, min: 1, fieldKind: 'numeric', fieldSize: 'xs' },
      { name: 'delivery_mode', label: 'Hình thức tổ chức', fieldKind: 'select', fieldSize: 'sm' },
      {
        name: 'status',
        label: 'Trạng thái',
        type: 'select',
        defaultValue: 'PLANNED',
        options: [
          { label: 'PLANNED', value: 'PLANNED' },
          { label: 'ACTIVE', value: 'ACTIVE' },
          { label: 'CANCELLED', value: 'CANCELLED' },
        ],
        fieldKind: 'status',
        fieldSize: 'sm',
      },
      { name: 'offering_code', label: 'Mã mở môn theo học kỳ', fieldKind: 'code', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'class_section_id', label: 'ID' },
      { key: 'class_code', label: 'Mã lớp' },
      { key: 'class_name', label: 'Tên lớp học phần' },
      { key: 'course.course_code', label: 'Mã môn' },
      { key: 'term.term_code', label: 'Học kỳ' },
      { key: 'capacity', label: 'Sức chứa' },
      { key: 'delivery_mode', label: 'Hình thức' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listClassSections(params),
      create: (form) => createClassSectionFromForm(form),
      update: (entityId, form) => updateClassSectionFromForm(entityId, form),
      deactivate: (entityId) => deactivateClassSection(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'enrollments',
    label: 'Ghi danh lớp học phần',
    group: 'Academic',
    primaryKey: 'enrollment_id',
    description: 'Sinh viên thuộc lớp học phần.',
    fields: [],
    createNote: 'Ghi danh thủ công theo lớp hiện dùng endpoint trong chi tiết lớp học phần; danh sách này dùng để kiểm tra dữ liệu import.',
    columns: [
      { key: 'enrollment_id', label: 'ID' },
      { key: 'class_code', label: 'Lớp học phần' },
      { key: 'student_code', label: 'Mã SV' },
      { key: 'full_name', label: 'Họ tên' },
      { key: 'enrollment_status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: deferred('Backend chỉ hỗ trợ tạo ghi danh trong ngữ cảnh lớp học phần chi tiết.'),
      update: unsupported('Backend không có PATCH enrollment riêng ở surface hiện tại.'),
      deactivate: deferred('Backend hỗ trợ deactivate enrollment theo lớp học phần, chưa nối ở surface này.'),
      readOnly: true,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: { list: ({ params }) => listEnrollments(params) },
  },
  {
    key: 'students',
    label: 'Sinh viên',
    group: 'People',
    primaryKey: 'student_id',
    description: 'Hồ sơ sinh viên; person_id là khóa để nối tài khoản người dùng sau này.',
    fields: [
      { name: 'full_name', label: 'Họ tên', required: true, fieldKind: 'longName', fieldSize: 'lg' },
      { name: 'student_code', label: 'Mã sinh viên', required: true, fieldKind: 'code', fieldSize: 'sm' },
      { name: 'date_of_birth', label: 'Ngày sinh', type: 'date', fieldKind: 'dateTime', fieldSize: 'md' },
      { name: 'gender_code', label: 'Giới tính', type: 'select', options: genderOptions, fieldKind: 'select', fieldSize: 'sm' },
      {
        name: 'program_id',
        label: 'Chương trình đào tạo',
        type: 'select',
        valueType: 'number',
        lookup: 'programs',
        integer: true,
        min: 1,
        allowManualLookupFallback: true,
        fieldKind: 'id',
        fieldSize: 'sm',
      },
      { name: 'cohort', label: 'Khóa', fieldKind: 'shortName', fieldSize: 'md' },
      { name: 'entry_year', label: 'Năm nhập học', type: 'number', integer: true, min: 1900, max: 2100, fieldKind: 'year', fieldSize: 'xs' },
      { name: 'student_status', label: 'Trạng thái SV', type: 'select', defaultValue: 'ACTIVE', options: statusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'student_id', label: 'Student ID' },
      { key: 'person_id', label: 'Person ID' },
      { key: 'student_code', label: 'Mã SV' },
      { key: 'full_name', label: 'Họ tên' },
      { key: 'program_code', label: 'CTĐT' },
      { key: 'student_status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listStudents(params),
      create: (form) => createStudentFromForm(form),
      update: (entityId, form) => updateStudentFromForm(entityId, form),
      deactivate: (entityId) => deactivateStudent(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'instructors',
    label: 'Giảng viên',
    group: 'People',
    primaryKey: 'instructor_id',
    description: 'Hồ sơ giảng viên; person_id là khóa để nối tài khoản người dùng sau này.',
    fields: [
      { name: 'full_name', label: 'Họ tên', required: true, fieldKind: 'longName', fieldSize: 'lg' },
      { name: 'instructor_code', label: 'Mã giảng viên', required: true, fieldKind: 'code', fieldSize: 'sm' },
      { name: 'date_of_birth', label: 'Ngày sinh', type: 'date', fieldKind: 'dateTime', fieldSize: 'md' },
      { name: 'gender_code', label: 'Giới tính', type: 'select', options: genderOptions, fieldKind: 'select', fieldSize: 'sm' },
      {
        name: 'department_id',
        label: 'Đơn vị',
        type: 'select',
        valueType: 'number',
        lookup: 'departments',
        integer: true,
        min: 1,
        allowManualLookupFallback: true,
        fieldKind: 'id',
        fieldSize: 'sm',
      },
      { name: 'instructor_status', label: 'Trạng thái GV', type: 'select', defaultValue: 'ACTIVE', options: statusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'instructor_id', label: 'Instructor ID' },
      { key: 'person_id', label: 'Person ID' },
      { key: 'instructor_code', label: 'Mã GV' },
      { key: 'full_name', label: 'Họ tên' },
      { key: 'department_code', label: 'Đơn vị' },
      { key: 'instructor_status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listInstructors(params),
      create: (form) => createInstructorFromForm(form),
      update: (entityId, form) => updateInstructorFromForm(entityId, form),
      deactivate: (entityId) => deactivateInstructor(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'assessment-types',
    label: 'Hình thức thi',
    group: 'Core',
    primaryKey: 'assessment_type_id',
    description: 'Danh mục hình thức đánh giá/thi dùng khi cấu hình đề và phiên thi.',
    fields: [],
    createNote: 'API hiện có endpoint xem danh mục hình thức thi; chưa có endpoint tạo mới.',
    columns: [
      { key: 'assessment_type_id', label: 'ID' },
      { key: 'type_code', label: 'Mã' },
      { key: 'type_name', label: 'Tên' },
      { key: 'description', label: 'Mô tả' },
      { key: 'is_active', label: 'Đang dùng' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: unsupported('Chưa có endpoint tạo assessment type trong master-data API.'),
      update: unsupported('Chưa có endpoint cập nhật assessment type trong master-data API.'),
      deactivate: unsupported('Chưa có endpoint deactivate assessment type trong master-data API.'),
      readOnly: true,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: false }),
    api: { list: ({ params }) => listAssessmentTypes(params) },
  },
  {
    key: 'exam-slots',
    label: 'Buổi thi',
    group: 'Core',
    primaryKey: 'slot_id',
    description: 'Danh mục ca/buổi thi cần API mới trước khi nối vào React.',
    fields: [],
    createNote: 'Chưa có endpoint master-data API cho buổi thi.',
    columns: [
      { key: 'slot_code', label: 'Mã buổi' },
      { key: 'slot_name', label: 'Tên buổi' },
      { key: 'start_time', label: 'Bắt đầu' },
      { key: 'end_time', label: 'Kết thúc' },
      { key: 'is_active', label: 'Đang dùng' },
    ],
    filters: [],
    capabilities: {
      list: unsupported('Chưa có endpoint master-data API cho buổi thi.'),
      create: unsupported('Chưa có endpoint master-data API cho buổi thi.'),
      update: unsupported('Chưa có endpoint master-data API cho buổi thi.'),
      deactivate: unsupported('Chưa có endpoint master-data API cho buổi thi.'),
      readOnly: true,
    },
    listFeatures: buildListFeatures({ supportsPagination: false }),
    api: {},
  },
  {
    key: 'rooms',
    label: 'Phòng thi / phòng máy',
    group: 'Facility',
    primaryKey: 'room_id',
    description: 'Danh sách phòng thi và phòng máy.',
    fields: [
      { name: 'room_code', label: 'Mã phòng', required: true, placeholder: 'VD: LAB-A101', fieldKind: 'code', fieldSize: 'sm' },
      { name: 'room_name', label: 'Tên phòng', required: true, fieldKind: 'longName', fieldSize: 'lg' },
      { name: 'building', label: 'Tòa nhà', fieldKind: 'shortName', fieldSize: 'md' },
      { name: 'floor_no', label: 'Tầng', fieldKind: 'numeric', fieldSize: 'xs' },
      { name: 'capacity', label: 'Sức chứa', type: 'number', integer: true, min: 0, fieldKind: 'numeric', fieldSize: 'xs' },
      { name: 'room_type', label: 'Loại phòng', type: 'select', defaultValue: 'LAB', options: roomTypeOptions, fieldKind: 'select', fieldSize: 'sm' },
      { name: 'status', label: 'Trạng thái', type: 'select', defaultValue: 'ACTIVE', options: facilityStatusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'room_id', label: 'ID' },
      { key: 'room_code', label: 'Mã phòng' },
      { key: 'room_name', label: 'Tên phòng' },
      { key: 'building', label: 'Tòa' },
      { key: 'capacity', label: 'Sức chứa' },
      { key: 'room_type', label: 'Loại' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listRooms(params),
      create: (form) => createRoomFromForm(form),
      update: (entityId, form) => updateRoomFromForm(entityId, form),
      deactivate: (entityId) => deactivateRoom(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'stations',
    label: 'Vị trí máy trạm',
    group: 'Facility',
    primaryKey: 'station_id',
    description: 'Danh sách vị trí máy trạm theo từng phòng.',
    fields: [
      { name: 'station_code', label: 'Mã chỗ ngồi', required: true, placeholder: 'VD: A101-01', fieldKind: 'code', fieldSize: 'sm' },
      { name: 'seat_no', label: 'Số ghế', fieldKind: 'order', fieldSize: 'xs' },
      { name: 'row_no', label: 'Hàng', fieldKind: 'order', fieldSize: 'xs' },
      { name: 'column_no', label: 'Cột', fieldKind: 'order', fieldSize: 'xs' },
      { name: 'status', label: 'Trạng thái', type: 'select', defaultValue: 'ACTIVE', options: stationStatusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'station_id', label: 'ID' },
      { key: 'room_code', label: 'Phòng' },
      { key: 'station_code', label: 'Mã chỗ' },
      { key: 'seat_no', label: 'Số ghế' },
      { key: 'row_no', label: 'Hàng' },
      { key: 'column_no', label: 'Cột' },
      { key: 'device.device_code', label: 'Thiết bị' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [{ key: 'room', label: 'Phòng thi / phòng máy', type: 'select' }],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true, defaultPageSize: 200, pageSizeOptions: [50, 100, 200] }),
    api: {
      list: ({ selectedRoomId, params }) => (selectedRoomId ? listRoomStations(selectedRoomId, params) : null),
      create: (form, { selectedRoomId }) => (selectedRoomId ? createRoomStationFromForm(selectedRoomId, form) : null),
      update: (entityId, form) => updateStationFromForm(entityId, form),
      deactivate: (entityId) => deactivateStation(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'devices',
    label: 'Thiết bị',
    group: 'Facility',
    primaryKey: 'device_id',
    description: 'Danh mục máy/thiết bị phục vụ phòng thi và liên kết chỗ ngồi.',
    fields: [
      { name: 'asset_tag', label: 'Mã tài sản', required: true, placeholder: 'VD: PC-A101-01', fieldKind: 'code', fieldSize: 'md' },
      { name: 'device_name', label: 'Tên thiết bị', fieldKind: 'longName', fieldSize: 'lg' },
      { name: 'device_type', label: 'Loại thiết bị', type: 'select', defaultValue: 'LAB_PC', options: deviceTypeOptions, fieldKind: 'select', fieldSize: 'sm' },
      { name: 'serial_no', label: 'Số serial', fieldKind: 'code', fieldSize: 'md' },
      { name: 'current_station_id', label: 'Vị trí hiện tại', type: 'number', integer: true, min: 1, helperText: 'Nhập ID hiện có trong hệ thống.', fieldKind: 'id', fieldSize: 'md' },
      { name: 'status', label: 'Trạng thái', type: 'select', defaultValue: 'ACTIVE', options: deviceStatusOptions, fieldKind: 'status', fieldSize: 'sm' },
    ],
    columns: [
      { key: 'device_id', label: 'ID' },
      { key: 'asset_tag', label: 'Mã tài sản' },
      { key: 'device_name', label: 'Tên' },
      { key: 'device_type', label: 'Loại' },
      { key: 'current_station_code', label: 'Chỗ ngồi' },
      { key: 'room_code', label: 'Phòng' },
      { key: 'status', label: 'Trạng thái' },
    ],
    filters: [],
    capabilities: {
      list: available(),
      create: available(),
      update: available(),
      deactivate: available(),
      readOnly: false,
    },
    listFeatures: buildListFeatures({ supportsQuery: true, supportsStatusFilter: true }),
    api: {
      list: ({ params }) => listDevices(params),
      create: (form) => createDeviceFromForm(form),
      update: (entityId, form) => updateDeviceFromForm(entityId, form),
      deactivate: (entityId) => deactivateDevice(entityId, { reason: 'Ngưng sử dụng từ giao diện quản trị.' }),
    },
  },
  {
    key: 'device-readiness',
    label: 'Kiểm tra thiết bị',
    group: 'Facility',
    primaryKey: 'station_id',
    description: 'Tình trạng sẵn sàng thiết bị theo phòng.',
    fields: [],
    createNote: 'Chọn phòng để xem trạng thái check-in thiết bị.',
    columns: [
      { key: 'room_code', label: 'Mã phòng' },
      { key: 'station_code', label: 'Vị trí' },
      { key: 'asset_tag', label: 'Mã tài sản' },
      { key: 'latest_checkin_at', label: 'Check-in gần nhất' },
      { key: 'latest_health_status', label: 'Trạng thái' },
      { key: 'station_mismatch', label: 'Sai vị trí' },
    ],
    filters: [{ key: 'room', label: 'Phòng thi / phòng máy', type: 'select' }],
    capabilities: {
      list: available(),
      create: unsupported('Surface này chỉ hiển thị tình trạng thiết bị.'),
      update: unsupported('Surface này chỉ hiển thị tình trạng thiết bị.'),
      deactivate: unsupported('Surface này chỉ hiển thị tình trạng thiết bị.'),
      readOnly: true,
    },
    listFeatures: buildListFeatures({ supportsPagination: false }),
    api: {
      list: ({ selectedRoomId }) => (selectedRoomId ? loadRoomStationReadiness(selectedRoomId) : null),
    },
  },
];

export const academicMasterDataEntities = masterDataEntities.filter((entity) =>
  ['departments', 'programs', 'courses', 'courseOfferings', 'classSections', 'enrollments', 'assessment-types', 'exam-slots'].includes(entity.key)
);

export const peopleMasterDataEntities = masterDataEntities.filter((entity) => ['students', 'instructors'].includes(entity.key));

export const facilityMasterDataEntities = masterDataEntities.filter((entity) =>
  ['rooms', 'stations', 'devices', 'device-readiness'].includes(entity.key)
);

export function findMasterDataEntity(key: EntityConfig['key']): EntityConfig {
  return masterDataEntities.find((config) => config.key === key) ?? masterDataEntities[0];
}
