-- Phase 1 source: docs/phase_1_database_architecture.md
-- Creates Phase 1 core tables using PostgreSQL-compatible types.

CREATE TABLE IF NOT EXISTS identity.person (
    person_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(255) NOT NULL,
    date_of_birth date NULL,
    gender_code varchar(30) NULL,
    national_id varchar(50) NULL,
    person_status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT ck_identity_person_status CHECK (person_status IN ('ACTIVE', 'INACTIVE', 'DECEASED', 'MERGED')),
    CONSTRAINT ck_identity_person_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.app_user (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    username varchar(100) NOT NULL,
    email_login varchar(255) NULL,
    password_hash varchar(500) NOT NULL,
    user_status varchar(30) NOT NULL,
    last_login_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_identity_app_user_username UNIQUE (username),
    CONSTRAINT ck_identity_app_user_status CHECK (user_status IN ('ACTIVE', 'LOCKED', 'DISABLED', 'PENDING')),
    CONSTRAINT ck_identity_app_user_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.role (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code varchar(50) NOT NULL,
    role_name varchar(255) NOT NULL,
    description varchar(1000) NULL,
    CONSTRAINT uq_identity_role_role_code UNIQUE (role_code)
);

CREATE TABLE IF NOT EXISTS identity.user_role (
    user_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    assigned_by bigint NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_identity_user_role_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS academic.department (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code varchar(50) NOT NULL,
    department_name varchar(255) NOT NULL,
    parent_department_id bigint NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_academic_department_department_code UNIQUE (department_code),
    CONSTRAINT ck_academic_department_status_nonempty CHECK (length(trim(status)) > 0),
    CONSTRAINT ck_academic_department_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.program (
    program_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id bigint NOT NULL,
    program_code varchar(50) NOT NULL,
    program_name varchar(255) NOT NULL,
    program_level varchar(50) NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_academic_program_program_code UNIQUE (program_code),
    CONSTRAINT ck_academic_program_level CHECK (
        program_level IS NULL OR program_level IN ('UNDERGRADUATE', 'MASTER', 'PHD', 'CERTIFICATE', 'SHORT_COURSE')
    ),
    CONSTRAINT ck_academic_program_status_nonempty CHECK (length(trim(status)) > 0),
    CONSTRAINT ck_academic_program_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.student_profile (
    student_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    student_code varchar(50) NOT NULL,
    program_id bigint NULL,
    cohort varchar(50) NULL,
    entry_year integer NULL,
    student_status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_identity_student_profile_student_code UNIQUE (student_code),
    CONSTRAINT ck_identity_student_profile_status CHECK (student_status IN ('ACTIVE', 'SUSPENDED', 'GRADUATED', 'WITHDRAWN')),
    CONSTRAINT ck_identity_student_profile_entry_year CHECK (entry_year IS NULL OR (entry_year >= 1900 AND entry_year <= 2100)),
    CONSTRAINT ck_identity_student_profile_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.instructor_profile (
    instructor_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    instructor_code varchar(50) NOT NULL,
    department_id bigint NULL,
    instructor_status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_identity_instructor_profile_instructor_code UNIQUE (instructor_code),
    CONSTRAINT ck_identity_instructor_profile_status CHECK (instructor_status IN ('ACTIVE', 'INACTIVE', 'VISITING', 'RETIRED')),
    CONSTRAINT ck_identity_instructor_profile_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.contact_point (
    contact_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    contact_type varchar(50) NOT NULL,
    contact_value varchar(255) NOT NULL,
    label varchar(100) NULL,
    is_primary boolean NOT NULL DEFAULT false,
    is_verified boolean NOT NULL DEFAULT false,
    valid_from timestamptz NULL,
    valid_to timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT ck_identity_contact_point_type CHECK (
        contact_type IN ('EMAIL', 'WORK_EMAIL', 'PERSONAL_EMAIL', 'PHONE', 'ZALO', 'PARENT_PHONE', 'EMERGENCY_PHONE')
    ),
    CONSTRAINT ck_identity_contact_point_valid_range CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_identity_contact_point_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.address (
    address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    address_type varchar(50) NOT NULL,
    address_line varchar(500) NOT NULL,
    ward varchar(255) NULL,
    district varchar(255) NULL,
    province varchar(255) NULL,
    country varchar(100) NULL,
    is_primary boolean NOT NULL DEFAULT false,
    valid_from timestamptz NULL,
    valid_to timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT ck_identity_address_type CHECK (address_type IN ('PERMANENT', 'CURRENT', 'MAILING', 'WORK')),
    CONSTRAINT ck_identity_address_valid_range CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_identity_address_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.term (
    term_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_code varchar(50) NOT NULL,
    term_name varchar(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_academic_term_term_code UNIQUE (term_code),
    CONSTRAINT ck_academic_term_status CHECK (status IN ('PLANNED', 'ACTIVE', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_academic_term_date_range CHECK (end_date >= start_date),
    CONSTRAINT ck_academic_term_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.course (
    course_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id bigint NOT NULL,
    course_code varchar(50) NOT NULL,
    course_name varchar(255) NOT NULL,
    course_type varchar(50) NULL,
    credit numeric(4,1) NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_academic_course_course_code UNIQUE (course_code),
    CONSTRAINT ck_academic_course_type CHECK (
        course_type IS NULL OR course_type IN ('SQL_SERVER', 'MISA', 'AMIS', 'ACCOUNTING', 'GENERAL')
    ),
    CONSTRAINT ck_academic_course_credit CHECK (credit IS NULL OR credit >= 0),
    CONSTRAINT ck_academic_course_status_nonempty CHECK (length(trim(status)) > 0),
    CONSTRAINT ck_academic_course_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.course_offering (
    course_offering_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL,
    term_id bigint NOT NULL,
    offering_code varchar(100) NOT NULL,
    coordinator_id bigint NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_academic_course_offering_offering_code UNIQUE (offering_code),
    CONSTRAINT ck_academic_course_offering_status_nonempty CHECK (length(trim(status)) > 0),
    CONSTRAINT ck_academic_course_offering_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.class_section (
    class_section_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_offering_id bigint NOT NULL,
    class_code varchar(100) NOT NULL,
    class_name varchar(255) NOT NULL,
    capacity integer NULL,
    delivery_mode varchar(50) NULL,
    status varchar(30) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_academic_class_section_class_code UNIQUE (class_code),
    CONSTRAINT ck_academic_class_section_capacity CHECK (capacity IS NULL OR capacity > 0),
    CONSTRAINT ck_academic_class_section_delivery_mode CHECK (
        delivery_mode IS NULL OR delivery_mode IN ('ONSITE', 'ONLINE', 'HYBRID', 'LAB')
    ),
    CONSTRAINT ck_academic_class_section_status CHECK (status IN ('PLANNED', 'ACTIVE', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_academic_class_section_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.class_enrollment (
    enrollment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_section_id bigint NOT NULL,
    student_id bigint NOT NULL,
    enrollment_status varchar(30) NOT NULL,
    enrolled_at timestamptz NOT NULL DEFAULT now(),
    dropped_at timestamptz NULL,
    note varchar(1000) NULL,
    CONSTRAINT uq_academic_class_enrollment_class_student UNIQUE (class_section_id, student_id),
    CONSTRAINT ck_academic_class_enrollment_status CHECK (enrollment_status IN ('ENROLLED', 'DROPPED', 'COMPLETED', 'TRANSFERRED')),
    CONSTRAINT ck_academic_class_enrollment_drop_time CHECK (dropped_at IS NULL OR dropped_at >= enrolled_at)
);

CREATE TABLE IF NOT EXISTS academic.teaching_assignment (
    teaching_assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_section_id bigint NOT NULL,
    instructor_id bigint NOT NULL,
    assignment_role varchar(50) NOT NULL,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    assigned_by bigint NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_academic_teaching_assignment_class_instructor_role UNIQUE (class_section_id, instructor_id, assignment_role),
    CONSTRAINT ck_academic_teaching_assignment_role CHECK (
        assignment_role IN ('LECTURER', 'ASSISTANT', 'COURSE_COORDINATOR', 'PRACTICE_INSTRUCTOR')
    )
);

CREATE TABLE IF NOT EXISTS academic.student_demographic_profile (
    student_demographic_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    gender_code varchar(30) NULL,
    nationality_code varchar(10) NULL,
    ethnicity_code varchar(50) NULL,
    native_place_code varchar(50) NULL,
    residence_region_code varchar(50) NULL,
    urban_rural_code varchar(30) NULL,
    valid_from date NOT NULL,
    valid_to date NULL,
    source varchar(50) NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_academic_student_demographic_valid_range CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS academic.student_prior_education (
    prior_education_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    entry_pathway_code varchar(50) NULL,
    previous_school_type varchar(50) NULL,
    previous_school_name varchar(255) NULL,
    previous_school_region varchar(50) NULL,
    previous_major varchar(255) NULL,
    entry_year integer NULL,
    entry_score numeric(10,2) NULL,
    placement_level_code varchar(50) NULL,
    english_level_code varchar(50) NULL,
    it_level_code varchar(50) NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT ck_academic_student_prior_education_entry_year CHECK (entry_year IS NULL OR (entry_year >= 1900 AND entry_year <= 2100)),
    CONSTRAINT ck_academic_student_prior_education_entry_score CHECK (entry_score IS NULL OR entry_score >= 0),
    CONSTRAINT ck_academic_student_prior_education_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS academic.student_socioeconomic_profile (
    socioeconomic_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    first_generation_flag boolean NULL,
    financial_aid_flag boolean NULL,
    scholarship_flag boolean NULL,
    tuition_support_type varchar(50) NULL,
    household_income_band varchar(50) NULL,
    parent_education_level varchar(50) NULL,
    employment_status varchar(50) NULL,
    working_hours_band varchar(50) NULL,
    dependent_care_flag boolean NULL,
    valid_from date NOT NULL,
    valid_to date NULL,
    source varchar(50) NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_academic_student_socioeconomic_valid_range CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS academic.student_learning_context (
    learning_context_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    primary_device_access varchar(50) NULL,
    internet_access_level varchar(50) NULL,
    commute_time_band varchar(50) NULL,
    preferred_learning_mode varchar(50) NULL,
    self_reported_it_confidence varchar(50) NULL,
    accounting_software_experience varchar(50) NULL,
    sql_experience_level varchar(50) NULL,
    valid_from date NOT NULL,
    valid_to date NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_academic_student_learning_context_valid_range CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE TABLE IF NOT EXISTS academic.student_accessibility_profile (
    accessibility_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    disability_disclosed_flag boolean NULL,
    support_need_type varchar(100) NULL,
    exam_accommodation_flag boolean NULL,
    extra_time_percent numeric(5,2) NULL,
    assistive_technology varchar(255) NULL,
    note_restricted text NULL,
    valid_from date NOT NULL,
    valid_to date NULL,
    approved_by bigint NULL,
    approved_at timestamptz NULL,
    CONSTRAINT ck_academic_student_accessibility_valid_range CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_academic_student_accessibility_extra_time CHECK (extra_time_percent IS NULL OR (extra_time_percent >= 0 AND extra_time_percent <= 500))
);

CREATE TABLE IF NOT EXISTS academic.student_consent (
    consent_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    consent_type varchar(100) NOT NULL,
    purpose_code varchar(100) NOT NULL,
    consent_status varchar(30) NOT NULL,
    given_at timestamptz NULL,
    withdrawn_at timestamptz NULL,
    version_no varchar(50) NULL,
    evidence_ref varchar(500) NULL,
    CONSTRAINT ck_academic_student_consent_purpose CHECK (
        purpose_code IN ('ACADEMIC_ADMINISTRATION', 'LEARNING_ANALYTICS', 'STUDENT_SUPPORT', 'RESEARCH_ANONYMIZED', 'EXAM_ACCOMMODATION')
    ),
    CONSTRAINT ck_academic_student_consent_status CHECK (consent_status IN ('GRANTED', 'WITHDRAWN', 'PENDING', 'DECLINED')),
    CONSTRAINT ck_academic_student_consent_withdraw_time CHECK (withdrawn_at IS NULL OR given_at IS NULL OR withdrawn_at >= given_at)
);

COMMENT ON TABLE identity.person IS 'Core person entity shared by students and instructors.';
COMMENT ON TABLE identity.app_user IS 'Login account mapped to person.';
COMMENT ON TABLE identity.role IS 'System roles (student, instructor, admin, etc.).';
COMMENT ON TABLE identity.user_role IS 'Many-to-many user role assignments.';
COMMENT ON TABLE identity.student_profile IS 'Academic student profile.';
COMMENT ON TABLE identity.instructor_profile IS 'Academic instructor profile.';
COMMENT ON TABLE identity.contact_point IS 'Multi-channel contact points per person.';
COMMENT ON TABLE identity.address IS 'Address records per person.';

COMMENT ON TABLE academic.department IS 'Academic department/unit.';
COMMENT ON TABLE academic.program IS 'Academic program under department.';
COMMENT ON TABLE academic.term IS 'Academic term/semester.';
COMMENT ON TABLE academic.course IS 'Course catalog entry.';
COMMENT ON TABLE academic.course_offering IS 'Course opened for a specific term.';
COMMENT ON TABLE academic.class_section IS 'Concrete class section of a course offering.';
COMMENT ON TABLE academic.class_enrollment IS 'Student enrollment in class section.';
COMMENT ON TABLE academic.teaching_assignment IS 'Instructor assignments per class section.';
COMMENT ON TABLE academic.student_demographic_profile IS 'Demographic context for analytics.';
COMMENT ON TABLE academic.student_prior_education IS 'Prior education context for analytics.';
COMMENT ON TABLE academic.student_socioeconomic_profile IS 'Socioeconomic context for analytics.';
COMMENT ON TABLE academic.student_learning_context IS 'Learning and technology context.';
COMMENT ON TABLE academic.student_accessibility_profile IS 'Accessibility accommodations and approvals.';
COMMENT ON TABLE academic.student_consent IS 'Consent records by purpose and status.';
