-- Add function-level RBAC tables and role metadata in identity schema (additive, idempotent).

ALTER TABLE IF EXISTS identity.role
    ADD COLUMN IF NOT EXISTS is_system_role boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz NULL;

DO
$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'identity'
          AND table_name = 'role'
          AND column_name = 'created_at'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'identity'
          AND t.relname = 'role'
          AND c.conname = 'ck_identity_role_updated_at'
    ) THEN
        ALTER TABLE identity.role
            ADD CONSTRAINT ck_identity_role_updated_at
            CHECK (updated_at IS NULL OR updated_at >= created_at);
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS identity.permission (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code varchar(120) NOT NULL,
    module_code varchar(60) NOT NULL,
    action_code varchar(60) NOT NULL,
    permission_name varchar(255) NOT NULL,
    description varchar(1000) NULL,
    is_sensitive boolean NOT NULL DEFAULT false,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NULL,
    CONSTRAINT uq_identity_permission_permission_code UNIQUE (permission_code),
    CONSTRAINT ck_identity_permission_permission_code_not_blank CHECK (length(trim(permission_code)) > 0),
    CONSTRAINT ck_identity_permission_module_code_not_blank CHECK (length(trim(module_code)) > 0),
    CONSTRAINT ck_identity_permission_action_code_not_blank CHECK (length(trim(action_code)) > 0),
    CONSTRAINT ck_identity_permission_permission_name_not_blank CHECK (length(trim(permission_name)) > 0),
    CONSTRAINT ck_identity_permission_updated_at CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE IF NOT EXISTS identity.role_permission (
    role_permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    granted_by bigint NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_identity_role_permission_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_identity_role_permission_role FOREIGN KEY (role_id)
        REFERENCES identity.role(role_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_identity_role_permission_permission FOREIGN KEY (permission_id)
        REFERENCES identity.permission(permission_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_identity_role_permission_granted_by FOREIGN KEY (granted_by)
        REFERENCES identity.app_user(user_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_identity_permission_permission_code
    ON identity.permission (permission_code);

CREATE INDEX IF NOT EXISTS idx_identity_permission_module_code_action_code
    ON identity.permission (module_code, action_code);

CREATE INDEX IF NOT EXISTS idx_identity_role_permission_role_id
    ON identity.role_permission (role_id);

CREATE INDEX IF NOT EXISTS idx_identity_role_permission_permission_id
    ON identity.role_permission (permission_id);

CREATE OR REPLACE VIEW identity.v_role_permission_summary AS
SELECT
    rp.role_permission_id,
    r.role_id,
    r.role_code,
    r.role_name,
    p.permission_id,
    p.permission_code,
    p.module_code,
    p.action_code,
    p.permission_name,
    p.is_sensitive,
    rp.is_active AS role_permission_is_active,
    r.is_active AS role_is_active,
    p.is_active AS permission_is_active,
    rp.granted_at,
    rp.granted_by
FROM identity.role_permission rp
JOIN identity.role r
    ON r.role_id = rp.role_id
JOIN identity.permission p
    ON p.permission_id = rp.permission_id;

COMMENT ON TABLE identity.permission IS
    'Function-level permission catalog for API/module actions.';

COMMENT ON COLUMN identity.permission.permission_code IS
    'Stable unique code for permission checks, for example imports:commit.';

COMMENT ON COLUMN identity.permission.module_code IS
    'Functional module owning the permission, for example imports, ops, grading.';

COMMENT ON COLUMN identity.permission.action_code IS
    'Action dimension of the permission, for example read, write, commit, execute.';

COMMENT ON COLUMN identity.permission.permission_name IS
    'Human-readable permission display name.';

COMMENT ON COLUMN identity.permission.is_sensitive IS
    'Marks permissions that grant high-risk or sensitive data operations.';

COMMENT ON TABLE identity.role_permission IS
    'Active grant mapping between identity.role and identity.permission.';

COMMENT ON COLUMN identity.role_permission.granted_by IS
    'Actor user_id that granted the permission mapping; nullable for system grants.';

COMMENT ON COLUMN identity.role_permission.is_active IS
    'Soft activation flag for grant mapping lifecycle without hard deletes.';

COMMENT ON COLUMN identity.role.is_system_role IS
    'True for built-in system roles managed by platform migrations.';

COMMENT ON COLUMN identity.role.is_active IS
    'Soft activation flag for role lifecycle.';

COMMENT ON COLUMN identity.role.created_at IS
    'Role creation timestamp.';

COMMENT ON COLUMN identity.role.updated_at IS
    'Latest role metadata update timestamp.';

COMMENT ON VIEW identity.v_role_permission_summary IS
    'Readonly-safe role-to-permission mapping summary without mutable token/session data.';

DO
$$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'exam_sys_app') THEN
        GRANT SELECT, INSERT, UPDATE ON TABLE identity.permission TO exam_sys_app;
        GRANT SELECT, INSERT, UPDATE ON TABLE identity.role_permission TO exam_sys_app;
        GRANT SELECT ON TABLE identity.v_role_permission_summary TO exam_sys_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA identity TO exam_sys_app;

        REVOKE DELETE ON TABLE identity.permission FROM exam_sys_app;
        REVOKE DELETE ON TABLE identity.role_permission FROM exam_sys_app;
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'exam_sys_readonly') THEN
        GRANT SELECT ON TABLE identity.permission TO exam_sys_readonly;

        -- Readonly operations should consume mapping through the summary view,
        -- not direct base-table access, to keep future internal grant metadata flexible.
        REVOKE SELECT ON TABLE identity.role_permission FROM exam_sys_readonly;
        GRANT SELECT ON TABLE identity.v_role_permission_summary TO exam_sys_readonly;
    END IF;
END
$$;

REVOKE ALL ON TABLE identity.permission FROM PUBLIC;
REVOKE ALL ON TABLE identity.role_permission FROM PUBLIC;
REVOKE ALL ON TABLE identity.v_role_permission_summary FROM PUBLIC;
